import {
  Shop,
  User,
  Product,
  Category,
  Brand,
  Customer,
  Supplier,
  Invoice,
  Purchase,
  CustomerTransaction,
  NotificationItem,
} from "@/types";

export const initialShop: Shop = {
  id: "shop-shree-ram-01",
  name: "Shree Ram Electric & Hardware",
  slug: "shree-ram-electric",
  ownerName: "Smit Panchal",
  email: "smitpanchal734@gmail.com",
  phone: "+91 98765 43210",
  address: "Shop No. 4, Mahavir Darshan, LBS Marg, Ghatkopar West",
  city: "Mumbai",
  state: "Maharashtra",
  pincode: "400086",
  gstin: "27AABCS1429B1Z8",
  pan: "AABCS1429B",
  invoicePrefix: "SRE-",
  nextInvoiceNumber: 1042,
  termsAndConditions:
    "1. Goods once sold will be tested before delivery.\n2. Warranty claims require original bill & packaging.\n3. Wires and cut items are non-returnable.\n4. Interest @ 18% p.a. charged on bills unpaid after 15 days.",
  plan: "PRO",
  active: true,
};

export const initialCategories: Category[] = [
  { id: "cat-1", shopId: initialShop.id, name: "Switches & Sockets", slug: "switches-sockets" },
  { id: "cat-2", shopId: initialShop.id, name: "Modular Plates", slug: "modular-plates" },
  { id: "cat-3", shopId: initialShop.id, name: "Wires & Cables", slug: "wires-cables" },
  { id: "cat-4", shopId: initialShop.id, name: "LED Lights & Bulbs", slug: "led-lights" },
  { id: "cat-5", shopId: initialShop.id, name: "MCBs, RCCBs & DB Boxes", slug: "mcb-rccb-db" },
  { id: "cat-6", shopId: initialShop.id, name: "Fan Regulators & Fans", slug: "fan-regulators" },
  { id: "cat-7", shopId: initialShop.id, name: "Adapters & Extension Boards", slug: "adapters-extensions" },
  { id: "cat-8", shopId: initialShop.id, name: "Conduits & Accessories", slug: "conduits-accessories" },
];

export const initialBrands: Brand[] = [
  { id: "b-1", shopId: initialShop.id, name: "Anchor Panasonic" },
  { id: "b-2", shopId: initialShop.id, name: "Havells" },
  { id: "b-3", shopId: initialShop.id, name: "Polycab" },
  { id: "b-4", shopId: initialShop.id, name: "Legrand" },
  { id: "b-5", shopId: initialShop.id, name: "Philips" },
  { id: "b-6", shopId: initialShop.id, name: "Finolex" },
  { id: "b-7", shopId: initialShop.id, name: "Schneider Electric" },
  { id: "b-8", shopId: initialShop.id, name: "Goldmedal" },
];

export const initialProducts: Product[] = [
  {
    id: "prod-1",
    shopId: initialShop.id,
    categoryId: "cat-1",
    brandId: "b-1",
    name: "Anchor Roma 6A 1-Way Switch",
    sku: "ANC-ROM-6A-SW",
    barcode: "890123456001",
    description: "Anchor Roma Classic 6A 240V White Switch",
    unit: "PIECE",
    purchasePrice: 22,
    retailPrice: 38,
    electricianPrice: 30,
    contractorPrice: 28,
    wholesalePrice: 26,
    gstRate: 18,
    hsnCode: "8536",
    openingStock: 250,
    currentStock: 184,
    minStockAlert: 50,
    warrantyMonths: 120, // 10 years mechanical warranty
    isActive: true,
  },
  {
    id: "prod-2",
    shopId: initialShop.id,
    categoryId: "cat-1",
    brandId: "b-1",
    name: "Anchor Roma 16A Power Switch",
    sku: "ANC-ROM-16A-SW",
    barcode: "890123456002",
    description: "Anchor Roma 16A Heavy Duty Switch with Indicator",
    unit: "PIECE",
    purchasePrice: 65,
    retailPrice: 110,
    electricianPrice: 90,
    contractorPrice: 85,
    wholesalePrice: 78,
    gstRate: 18,
    hsnCode: "8536",
    openingStock: 100,
    currentStock: 42,
    minStockAlert: 20,
    warrantyMonths: 120,
    isActive: true,
  },
  {
    id: "prod-3",
    shopId: initialShop.id,
    categoryId: "cat-1",
    brandId: "b-1",
    name: "Anchor Roma 6A 3-Pin Socket with Shutter",
    sku: "ANC-ROM-6A-SOC",
    barcode: "890123456003",
    description: "Safety shutter 6A 3 Pin Socket",
    unit: "PIECE",
    purchasePrice: 42,
    retailPrice: 75,
    electricianPrice: 60,
    contractorPrice: 56,
    wholesalePrice: 52,
    gstRate: 18,
    hsnCode: "8536",
    openingStock: 150,
    currentStock: 8, // Low Stock Trigger
    minStockAlert: 25,
    warrantyMonths: 60,
    isActive: true,
  },
  {
    id: "prod-4",
    shopId: initialShop.id,
    categoryId: "cat-1",
    brandId: "b-1",
    name: "Anchor Roma 16A Combo Socket",
    sku: "ANC-ROM-16A-SOC",
    barcode: "890123456004",
    description: "6A/16A Universal Heavy Socket",
    unit: "PIECE",
    purchasePrice: 82,
    retailPrice: 145,
    electricianPrice: 120,
    contractorPrice: 112,
    wholesalePrice: 102,
    gstRate: 18,
    hsnCode: "8536",
    openingStock: 80,
    currentStock: 56,
    minStockAlert: 15,
    warrantyMonths: 60,
    isActive: true,
  },
  {
    id: "prod-5",
    shopId: initialShop.id,
    categoryId: "cat-2",
    brandId: "b-1",
    name: "Anchor Roma 4-Module Modular Plate",
    sku: "ANC-ROM-PLT-4M",
    barcode: "890123456005",
    description: "Pure White Finish 4M Cover Plate with Base Frame",
    unit: "PIECE",
    purchasePrice: 48,
    retailPrice: 85,
    electricianPrice: 70,
    contractorPrice: 65,
    wholesalePrice: 60,
    gstRate: 18,
    hsnCode: "8538",
    openingStock: 120,
    currentStock: 64,
    minStockAlert: 20,
    warrantyMonths: 24,
    isActive: true,
  },
  {
    id: "prod-6",
    shopId: initialShop.id,
    categoryId: "cat-2",
    brandId: "b-1",
    name: "Anchor Roma 8-Module Horizontal Plate",
    sku: "ANC-ROM-PLT-8M",
    barcode: "890123456006",
    description: "8M Frame + Cover Plate White",
    unit: "PIECE",
    purchasePrice: 88,
    retailPrice: 155,
    electricianPrice: 128,
    contractorPrice: 118,
    wholesalePrice: 108,
    gstRate: 18,
    hsnCode: "8538",
    openingStock: 90,
    currentStock: 38,
    minStockAlert: 15,
    warrantyMonths: 24,
    isActive: true,
  },
  // WIRE - METER BASED
  {
    id: "prod-7",
    shopId: initialShop.id,
    categoryId: "cat-3",
    brandId: "b-2",
    name: "Havells LifeLine Plus 1.5 sq.mm FR Copper Wire",
    sku: "HAV-WIRE-1.5-RED",
    barcode: "890123456007",
    description: "Flame Retardant 1.5 sq.mm single core wire - Sold by Meter",
    unit: "METER",
    purchasePrice: 20.5,
    retailPrice: 32.0,
    electricianPrice: 26.5,
    contractorPrice: 25.0,
    wholesalePrice: 23.5,
    gstRate: 18,
    hsnCode: "8544",
    openingStock: 1000,
    currentStock: 685, // in meters
    minStockAlert: 150,
    isCable: true,
    cableType: "Copper Single Core FR",
    coreCount: 1,
    crossSection: "1.5 sq.mm",
    wireColor: "Red",
    warrantyMonths: 60,
    isActive: true,
  },
  {
    id: "prod-8",
    shopId: initialShop.id,
    categoryId: "cat-3",
    brandId: "b-3",
    name: "Polycab Flame Retardant 2.5 sq.mm Wire",
    sku: "POL-WIRE-2.5-BLU",
    barcode: "890123456008",
    description: "2.5 sq.mm Heavy Phase Wire - Sold by Meter",
    unit: "METER",
    purchasePrice: 33.0,
    retailPrice: 50.0,
    electricianPrice: 42.0,
    contractorPrice: 39.5,
    wholesalePrice: 37.0,
    gstRate: 18,
    hsnCode: "8544",
    openingStock: 800,
    currentStock: 432, // in meters
    minStockAlert: 100,
    isCable: true,
    cableType: "Copper Single Core FRLS",
    coreCount: 1,
    crossSection: "2.5 sq.mm",
    wireColor: "Blue",
    warrantyMonths: 60,
    isActive: true,
  },
  {
    id: "prod-9",
    shopId: initialShop.id,
    categoryId: "cat-3",
    brandId: "b-6",
    name: "Finolex 4.0 sq.mm Heavy Load Wire",
    sku: "FIN-WIRE-4.0-BLK",
    barcode: "890123456009",
    description: "4.0 sq.mm AC / Geyser Heavy Load wire - Sold by Meter",
    unit: "METER",
    purchasePrice: 52.0,
    retailPrice: 78.0,
    electricianPrice: 66.0,
    contractorPrice: 62.0,
    wholesalePrice: 58.0,
    gstRate: 18,
    hsnCode: "8544",
    openingStock: 500,
    currentStock: 0, // OUT OF STOCK Trigger!
    minStockAlert: 80,
    isCable: true,
    cableType: "Copper Single Core FRLS",
    coreCount: 1,
    crossSection: "4.0 sq.mm",
    wireColor: "Black",
    warrantyMonths: 60,
    isActive: true,
  },
  // LED LIGHTS
  {
    id: "prod-10",
    shopId: initialShop.id,
    categoryId: "cat-4",
    brandId: "b-5",
    name: "Philips Stellar Bright 9W B22 LED Bulb",
    sku: "PHI-LED-9W-B22",
    barcode: "890123456010",
    description: "6500K Cool Day Light, Energy Saving LED Bulb",
    unit: "PIECE",
    purchasePrice: 62,
    retailPrice: 110,
    electricianPrice: 90,
    contractorPrice: 85,
    wholesalePrice: 80,
    gstRate: 12,
    hsnCode: "8539",
    openingStock: 120,
    currentStock: 74,
    minStockAlert: 20,
    warrantyMonths: 12,
    isActive: true,
  },
  {
    id: "prod-11",
    shopId: initialShop.id,
    categoryId: "cat-4",
    brandId: "b-2",
    name: "Havells Adore 12W Concealed Downlight",
    sku: "HAV-LED-12W-DL",
    barcode: "890123456011",
    description: "Round False Ceiling LED Spot Light 12W",
    unit: "PIECE",
    purchasePrice: 195,
    retailPrice: 340,
    electricianPrice: 280,
    contractorPrice: 260,
    wholesalePrice: 245,
    gstRate: 12,
    hsnCode: "8539",
    openingStock: 60,
    currentStock: 28,
    minStockAlert: 10,
    warrantyMonths: 24,
    isActive: true,
  },
  // MCB & SAFETY
  {
    id: "prod-12",
    shopId: initialShop.id,
    categoryId: "cat-5",
    brandId: "b-4",
    name: "Legrand RX3 16A Single Pole MCB (C-Curve)",
    sku: "LEG-MCB-16A-SP",
    barcode: "890123456012",
    description: "10kA Short Circuit Breaking Capacity C-16A",
    unit: "PIECE",
    purchasePrice: 145,
    retailPrice: 240,
    electricianPrice: 205,
    contractorPrice: 195,
    wholesalePrice: 180,
    gstRate: 18,
    hsnCode: "8536",
    openingStock: 75,
    currentStock: 32,
    minStockAlert: 15,
    warrantyMonths: 24,
    isActive: true,
  },
  {
    id: "prod-13",
    shopId: initialShop.id,
    categoryId: "cat-5",
    brandId: "b-4",
    name: "Legrand RX3 32A Double Pole MCB",
    sku: "LEG-MCB-32A-DP",
    barcode: "890123456013",
    description: "Double Pole Main Isolator/MCB 32 Ampere",
    unit: "PIECE",
    purchasePrice: 380,
    retailPrice: 620,
    electricianPrice: 520,
    contractorPrice: 490,
    wholesalePrice: 460,
    gstRate: 18,
    hsnCode: "8536",
    openingStock: 30,
    currentStock: 14,
    minStockAlert: 5,
    warrantyMonths: 24,
    isActive: true,
  },
  // REGULATORS & ACCESSORIES
  {
    id: "prod-14",
    shopId: initialShop.id,
    categoryId: "cat-6",
    brandId: "b-1",
    name: "Anchor Roma 4-Step 100W Fan Step Regulator",
    sku: "ANC-ROM-REG-100W",
    barcode: "890123456014",
    description: "Hum Free Rotary Modular Step Regulator (1 Module)",
    unit: "PIECE",
    purchasePrice: 185,
    retailPrice: 310,
    electricianPrice: 260,
    contractorPrice: 245,
    wholesalePrice: 230,
    gstRate: 18,
    hsnCode: "8414",
    openingStock: 50,
    currentStock: 19,
    minStockAlert: 8,
    warrantyMonths: 24,
    isActive: true,
  },
  {
    id: "prod-15",
    shopId: initialShop.id,
    categoryId: "cat-7",
    brandId: "b-8",
    name: "Goldmedal Curve 4+1 Power Strip Extension Cord (2M)",
    sku: "GLD-EXT-4+1-2M",
    barcode: "890123456015",
    description: "4 Sockets + Master Switch with LED indicator & Surge Protector",
    unit: "PIECE",
    purchasePrice: 290,
    retailPrice: 490,
    electricianPrice: 420,
    contractorPrice: 395,
    wholesalePrice: 370,
    gstRate: 18,
    hsnCode: "8536",
    openingStock: 40,
    currentStock: 22,
    minStockAlert: 6,
    warrantyMonths: 12,
    isActive: true,
  },
  {
    id: "prod-16",
    shopId: initialShop.id,
    categoryId: "cat-8",
    brandId: "b-1",
    name: "Anchor Heavy Duty PVC Insulation Tape (Red, 8m)",
    sku: "ANC-TAPE-RED",
    barcode: "890123456016",
    description: "FR Grade Moisture Resistant PVC Electrical Tape",
    unit: "PIECE",
    purchasePrice: 8.5,
    retailPrice: 15.0,
    electricianPrice: 12.0,
    contractorPrice: 11.0,
    wholesalePrice: 10.0,
    gstRate: 18,
    hsnCode: "3919",
    openingStock: 300,
    currentStock: 145,
    minStockAlert: 50,
    warrantyMonths: 0,
    isActive: true,
  },
];

export const initialCustomers: Customer[] = [
  {
    id: "cust-1",
    shopId: initialShop.id,
    name: "Suresh Patil (Patil Electrical Works)",
    phone: "9820123456",
    email: "patilelectric@gmail.com",
    address: "R-12, Sector 4, Kopar Khairane",
    customerType: "ELECTRICIAN",
    creditLimit: 50000,
    currentUdhaar: 8450,
    commissionBalance: 3240, // ₹3,240 Commission Earned
    totalPurchases: 64200,
    totalPaid: 55750,
    notes: "VIP Electrician. Regular weekly buyer. Gives bulk wiring contracts.",
    createdAt: "2026-08-15T10:00:00Z",
  },
  {
    id: "cust-2",
    shopId: initialShop.id,
    name: "Mayur Shah (Shah Developers & Contractors)",
    phone: "9819876543",
    email: "mayur@shahbuilders.in",
    address: "B-501, Neelkanth Heights, Thane West",
    customerType: "CONTRACTOR",
    gstin: "27AAYCS9876C1Z4",
    creditLimit: 200000,
    currentUdhaar: 42300,
    totalPurchases: 320000,
    totalPaid: 277700,
    notes: "Contractor pricing. Net 30 days payment terms.",
    createdAt: "2026-07-20T11:30:00Z",
  },
  {
    id: "cust-3",
    shopId: initialShop.id,
    name: "Ramesh Sharma",
    phone: "9870011223",
    address: "Flat 302, Sai Shraddha, Ghatkopar",
    customerType: "NORMAL",
    creditLimit: 5000,
    currentUdhaar: 0,
    totalPurchases: 3850,
    totalPaid: 3850,
    notes: "Local retail walk-in customer.",
    createdAt: "2026-09-10T14:15:00Z",
  },
  {
    id: "cust-4",
    shopId: initialShop.id,
    name: "Ganesh Mhatre (Ganesh Enterprises)",
    phone: "9768005544",
    customerType: "ELECTRICIAN",
    creditLimit: 30000,
    currentUdhaar: 12500,
    totalPurchases: 48900,
    totalPaid: 36400,
    notes: "Local area maintenance technician.",
    createdAt: "2026-09-01T09:45:00Z",
  },
];

export const initialSuppliers: Supplier[] = [
  {
    id: "sup-1",
    shopId: initialShop.id,
    name: "Apex Electrical Wholesalers",
    company: "Apex Distributors Pvt Ltd",
    phone: "022-22019988",
    email: "sales@apexdistributors.com",
    address: "14 Lohar Chawl, Kalbadevi, Mumbai 400002",
    gstin: "27AAACA1234D1Z2",
    totalPurchases: 450000,
    pendingAmount: 38500,
  },
  {
    id: "sup-2",
    shopId: initialShop.id,
    name: "Cable House Mumbai",
    company: "Polycab & Havells Authorized Stockist",
    phone: "022-22067744",
    email: "orders@cablehouse.in",
    address: "22 Pathakwadi, Lohar Chawl, Mumbai",
    gstin: "27AACCB4321E1Z9",
    totalPurchases: 680000,
    pendingAmount: 14200,
  },
];

export const initialInvoices: Invoice[] = [
  {
    id: "inv-1040",
    shopId: initialShop.id,
    customerId: "cust-1",
    invoiceNumber: "SRE-1040",
    invoiceDate: new Date(Date.now() - 3600000 * 24).toISOString(),
    customerName: "Suresh Patil (Patil Electrical Works)",
    customerPhone: "9820123456",
    customerType: "ELECTRICIAN",
    subtotal: 4280,
    discountAmount: 100,
    taxableAmount: 3542.37,
    cgstAmount: 318.81,
    sgstAmount: 318.81,
    igstAmount: 0,
    totalTax: 637.62,
    roundOff: 0,
    grandTotal: 4180,
    paymentMethod: "UPI",
    paymentStatus: "PAID",
    paidAmount: 4180,
    dueAmount: 0,
    notes: "Site: Neelkanth Valley Flat 204",
    items: [
      {
        id: "item-1",
        productId: "prod-1",
        productName: "Anchor Roma 6A 1-Way Switch",
        sku: "ANC-ROM-6A-SW",
        hsnCode: "8536",
        unit: "PIECE",
        quantity: 20,
        rate: 30, // Electrician rate
        discountAmount: 0,
        taxableValue: 508.47,
        gstRate: 18,
        gstAmount: 91.53,
        total: 600,
        warrantyMonths: 120,
      },
      {
        id: "item-2",
        productId: "prod-7",
        productName: "Havells LifeLine Plus 1.5 sq.mm FR Copper Wire",
        sku: "HAV-WIRE-1.5-RED",
        hsnCode: "8544",
        unit: "METER",
        quantity: 90, // Full 90m roll
        rate: 26.5,
        discountAmount: 0,
        taxableValue: 2021.18,
        gstRate: 18,
        gstAmount: 363.82,
        total: 2385,
        warrantyMonths: 60,
      },
      {
        id: "item-3",
        productId: "prod-10",
        productName: "Philips Stellar Bright 9W B22 LED Bulb",
        sku: "PHI-LED-9W-B22",
        hsnCode: "8539",
        unit: "PIECE",
        quantity: 14,
        rate: 90,
        discountAmount: 100,
        taxableValue: 1035.71,
        gstRate: 12,
        gstAmount: 124.29,
        total: 1160,
        warrantyMonths: 12,
      },
    ],
  },
  {
    id: "inv-1041",
    shopId: initialShop.id,
    customerId: "cust-2",
    invoiceNumber: "SRE-1041",
    invoiceDate: new Date(Date.now() - 3600000 * 5).toISOString(),
    customerName: "Mayur Shah (Shah Developers)",
    customerPhone: "9819876543",
    customerType: "CONTRACTOR",
    customerGstin: "27AAYCS9876C1Z4",
    subtotal: 18450,
    discountAmount: 450,
    taxableAmount: 15254.24,
    cgstAmount: 1372.88,
    sgstAmount: 1372.88,
    igstAmount: 0,
    totalTax: 2745.76,
    roundOff: 0,
    grandTotal: 18000,
    paymentMethod: "UDHAAR",
    paymentStatus: "UNPAID",
    paidAmount: 0,
    dueAmount: 18000,
    notes: "Phase 2 Wiring Project. Udhaar added to ledger.",
    items: [
      {
        id: "item-4",
        productId: "prod-8",
        productName: "Polycab Flame Retardant 2.5 sq.mm Wire",
        sku: "POL-WIRE-2.5-BLU",
        hsnCode: "8544",
        unit: "METER",
        quantity: 200,
        rate: 39.5, // Contractor rate
        discountAmount: 0,
        taxableValue: 6694.91,
        gstRate: 18,
        gstAmount: 1205.09,
        total: 7900,
        warrantyMonths: 60,
      },
      {
        id: "item-5",
        productId: "prod-12",
        productName: "Legrand RX3 16A Single Pole MCB (C-Curve)",
        sku: "LEG-MCB-16A-SP",
        hsnCode: "8536",
        unit: "PIECE",
        quantity: 24,
        rate: 195,
        discountAmount: 0,
        taxableValue: 3966.1,
        gstRate: 18,
        gstAmount: 713.9,
        total: 4680,
        warrantyMonths: 24,
      },
      {
        id: "item-6",
        productId: "prod-13",
        productName: "Legrand RX3 32A Double Pole MCB",
        sku: "LEG-MCB-32A-DP",
        hsnCode: "8536",
        unit: "PIECE",
        quantity: 12,
        rate: 490,
        discountAmount: 450,
        taxableValue: 4601.69,
        gstRate: 18,
        gstAmount: 828.31,
        total: 5430,
        warrantyMonths: 24,
      },
    ],
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: "notif-1",
    type: "OUT_OF_STOCK",
    title: "Stock Alert: Finolex 4.0 sq.mm Wire",
    message: "Current stock is 0 meters. Reorder immediately from Cable House.",
    isRead: false,
    timestamp: "10 mins ago",
    linkUrl: "/products",
  },
  {
    id: "notif-2",
    type: "LOW_STOCK",
    title: "Low Stock: Anchor Roma 6A 3-Pin Socket",
    message: "Only 8 pieces left in inventory (Minimum alert: 25).",
    isRead: false,
    timestamp: "1 hour ago",
    linkUrl: "/products",
  },
  {
    id: "notif-3",
    type: "PENDING_PAYMENT",
    title: "Udhaar Pending: Shah Developers",
    message: "Pending balance has reached ₹42,300. Credit limit is ₹2,00,000.",
    isRead: false,
    timestamp: "3 hours ago",
    linkUrl: "/credit",
  },
];
